# Generated by Django 2.0.2 on 2019-07-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部门名')),
                ('month', models.IntegerField(default=0, verbose_name='考核月份')),
                ('points', models.FloatField(null=True, verbose_name='考核分数')),
                ('departmentclass', models.CharField(max_length=40, verbose_name='部门分类')),
                ('rank', models.IntegerField(null=True, verbose_name='部门考核排名')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部门名')),
                ('month', models.IntegerField(default=0, verbose_name='考核月份')),
                ('grade', models.IntegerField(default=0, verbose_name='部门得分')),
                ('managerid', models.CharField(max_length=40, verbose_name='部门经理')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='员工姓名')),
                ('jobnum', models.CharField(max_length=40, verbose_name='员工ID')),
                ('department', models.CharField(max_length=50, null=True, verbose_name='员工所属部门')),
                ('managerid', models.CharField(max_length=40, null=True, verbose_name='部门经理')),
                ('attendance', models.BooleanField(default=False, verbose_name='是否出勤')),
                ('mgrade', models.IntegerField(null=True, verbose_name='经理打分')),
                ('month', models.IntegerField(default=0, null=True, verbose_name='考核月份')),
                ('lastinfo', models.IntegerField(default=0, null=True, verbose_name='对应渲染用户')),
            ],
        ),
        migrations.CreateModel(
            name='MarkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='员工姓名')),
                ('jobnum', models.CharField(max_length=40, verbose_name='员工ID')),
                ('department', models.CharField(max_length=50, null=True, verbose_name='员工所属部门')),
                ('level', models.CharField(max_length=40, null=True, verbose_name='评级')),
                ('jifen', models.IntegerField(null=True, verbose_name='积分')),
                ('mgrade', models.IntegerField(null=True, verbose_name='经理打分')),
                ('month', models.IntegerField(default=0, null=True, verbose_name='考核月份')),
                ('lastinfo', models.IntegerField(default=0, null=True, verbose_name='对应渲染用户')),
            ],
        ),
    ]
