# Generated by Django 2.0.2 on 2019-11-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
    ]
